/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flaggame;
import java.util.Random;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
/**
 *
 * @author Nathan Cabral
 */
public class GameInterface extends javax.swing.JFrame {

    /**
     * Creates new form GameInterface
     */
    
    static int milliseconds = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;
    
    static boolean state = true;
    
    public GameInterface() {
        initComponents();
        this.setTitle("Flag Game");
        studentName();
        numOfFlags();
        nextQuestion();
       String score = String.valueOf(questionCounter);
       numberOfFlagsScor.setText(score);
       String totNumFlags = String.valueOf(numOfFlagsChosen);
       scoreOutOf.setText(totNumFlags);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        flagPicture = new javax.swing.JLabel();
        btnAns1 = new javax.swing.JRadioButton();
        btnAns2 = new javax.swing.JRadioButton();
        btnAns3 = new javax.swing.JRadioButton();
        btnAns4 = new javax.swing.JRadioButton();
        submitQuestion = new javax.swing.JButton();
        endQuiz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberOfFlagsScor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scoreOutOf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(377, 316));

        flagPicture.setBackground(new java.awt.Color(153, 153, 255));

        buttonGroup1.add(btnAns1);
        btnAns1.setText("Answer1");
        btnAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAns1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAns2);
        btnAns2.setText("Answer2");
        btnAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAns2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAns3);
        btnAns3.setText("Answer3");
        btnAns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAns3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAns4);
        btnAns4.setText("Answer4");
        btnAns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAns4ActionPerformed(evt);
            }
        });

        submitQuestion.setText("Submit");
        submitQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuestionActionPerformed(evt);
            }
        });

        endQuiz.setText("End Quiz");

        jLabel1.setText("Last Question Status:");

        jLabel2.setText("Question");

        numberOfFlagsScor.setText("InS");

        jLabel3.setText("out of");

        scoreOutOf.setText("SoF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endQuiz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitQuestion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(numberOfFlagsScor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoreOutOf))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAns3)
                    .addComponent(btnAns1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAns2)
                    .addComponent(btnAns4))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(flagPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfFlagsScor)
                    .addComponent(jLabel3)
                    .addComponent(scoreOutOf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flagPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAns1)
                    .addComponent(btnAns2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAns3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAns4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitQuestion)
                    .addComponent(endQuiz))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAns4ActionPerformed
        studentAnswer = 4;
    }//GEN-LAST:event_btnAns4ActionPerformed

    private void btnAns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAns3ActionPerformed
        studentAnswer = 3;
    }//GEN-LAST:event_btnAns3ActionPerformed

    private void btnAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAns1ActionPerformed
        studentAnswer = 1;
    }//GEN-LAST:event_btnAns1ActionPerformed

    private void btnAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAns2ActionPerformed
        studentAnswer = 2;
    }//GEN-LAST:event_btnAns2ActionPerformed

    private void submitQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuestionActionPerformed
       boolean answerStatus;
       
       if(studentAnswer == answerPlace)
       {
           answerStatus = true;
           studentScore = studentScore + 1;
           Status.setText("Correct");
           
       }
       else
       {
           answerStatus = false;
           Status.setText("Incorrect");
       }
       
       if(questionCounter < numOfFlagsChosen )
       {
           questionCounter = questionCounter + 1;   
           nextQuestion();
       }
       else
       {
        exportInformation();
        this.setVisible(false);
        new Score(numOfFlagsChosen, studentScore).setVisible(true);
       }
       String score = String.valueOf(questionCounter);
       numberOfFlagsScor.setText(score);
       String totNumFlags = String.valueOf(numOfFlagsChosen);
       scoreOutOf.setText(totNumFlags);
       //jProgressBar1.setValue(questionCounter + 1);
       //ProgressBar1.setMaximum(numOfFlagsChosen);
    }//GEN-LAST:event_submitQuestionActionPerformed
    
    public void nextQuestion()
    {
        
        GameData.FG.correctAnswer();
        GameData.FG.getRandomAns();
        setFlag();
        
    }
    public void exportInformation()
    {
        try
        {
            String outputFile = "FlagGameResults.txt";
            PrintWriter outputWriter;
            outputWriter = new PrintWriter(outputFile);
            String date = GameResult.studentResult.dateAndTimeCompilation();
            String outputMessage =(studentName + "   " + studentScore + "/" + numOfFlagsChosen + "   " + date );
            GameData.quizResults.add(outputMessage);
            for (String i: GameData.quizResults)
            {
                outputWriter.println(i);
            }
            outputWriter.close();
          
        }
        catch(Exception noFileFound)
        {
            System.out.println("Error Writing File");
        }
    }
    
    public void numOfFlags()
    {
        String numberOfFlags = JOptionPane.showInputDialog("How many flags would you like to quiz on? (Choose between 1 and 197)");
        numOfFlagsChosen = Integer.parseInt(numberOfFlags);
        if (numOfFlagsChosen > 197)
        {
            numOfFlags();
        }
        state = true;
        Thread timer = new  Thread()
        {
           public void run()
           {
               
               for(;;)
               {
                  if(state == true)
                    {
                        try
                        {
                            sleep(1);
                            if(milliseconds>1000)
                            {
                                milliseconds = 0;
                                seconds++;
                            }
                            if(seconds>60)
                            {
                                milliseconds = 0;
                                seconds = 0;
                                minutes++;
                            }
                            if(minutes>60)
                            {
                                milliseconds = 0;
                                seconds = 0;
                                minutes = 0;
                                hours++;
                            }
                            
                           
                           milliseconds++; 
                        }
                        catch(Exception e)
                        {
                            
                        }
                    } 
                  else
                  {
                      break;
                  }
               }
                   
           }
        };
       
    }
        
    public void studentName()
    {
        studentName = JOptionPane.showInputDialog("Please Enter Name:");
        if (studentName == null)
        {
            studentName();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInterface().setVisible(true);
                
            }
        });
    }
    
    public void setFlag()
    {
        Flag question = GameData.FG.getFlag();
        System.out.print(question);
        flagPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource(question.getFlagFile())));
        answerPlace = 1 + answerGenerator.nextInt(4);
        
        if(answerPlace == 1)
        {
            
            btnAns1.setText(GameData.FG.getCorrectAnswer());
            btnAns2.setText(GameData.FG.getCurrentFlagArray(1));
            btnAns3.setText(GameData.FG.getCurrentFlagArray(2));
            btnAns4.setText(GameData.FG.getCurrentFlagArray(3));
            
        }
        else if(answerPlace == 2)
        {
            
            btnAns1.setText(GameData.FG.getCurrentFlagArray(1));
            btnAns2.setText(GameData.FG.getCorrectAnswer());
            btnAns3.setText(GameData.FG.getCurrentFlagArray(2));
            btnAns4.setText(GameData.FG.getCurrentFlagArray(3));
            
        }
        else if(answerPlace == 3)
        {
            
            btnAns1.setText(GameData.FG.getCurrentFlagArray(1));
            btnAns2.setText(GameData.FG.getCurrentFlagArray(2));
            btnAns3.setText(GameData.FG.getCorrectAnswer());
            btnAns4.setText(GameData.FG.getCurrentFlagArray(3));
            
        }
        else if(answerPlace == 4)
        {
            
            btnAns1.setText(GameData.FG.getCurrentFlagArray(1));
            btnAns2.setText(GameData.FG.getCurrentFlagArray(2));
            btnAns3.setText(GameData.FG.getCurrentFlagArray(3));
            btnAns4.setText(GameData.FG.getCorrectAnswer());
            
        }
        
    }
    int studentAnswer;
    int answerPlace;
    int questionCounter = 1;
    int numOfFlagsChosen;
    String studentName;
    int studentScore;
    Random answerGenerator = new Random();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JRadioButton btnAns1;
    private javax.swing.JRadioButton btnAns2;
    private javax.swing.JRadioButton btnAns3;
    private javax.swing.JRadioButton btnAns4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton endQuiz;
    private javax.swing.JLabel flagPicture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel numberOfFlagsScor;
    private javax.swing.JLabel scoreOutOf;
    private javax.swing.JButton submitQuestion;
    // End of variables declaration//GEN-END:variables
}
